### ISSUE TITLE
Feature Request: Write to Output Directory

### ISSUE THREAD

**Issue by jpoling-dswrx** [nccgroup/Scout2#109] opened 2016-09-15 16:41 UTC
It would be great if we could specify an output dir, a la `-D <dir>` to which the report and all related files would be written so the singular folder itself could be easily copied over to and viewed on separate systems.

**Comment by l01cd3v** [comment] 2016-09-18 22:09
Duplicate of #84, which is an enhancement I may implement at some point. PR are accepted. closing this one for now.

**Closed by l01cd3v** 2016-09-18 22:09 UTC
Labels: duplicate
