### ISSUE TITLE
VPC subnet without a flow log - wrong finding

### ISSUE THREAD

**Issue by fkpp** [nccgroup/Scout2#251] opened 2018-03-16 12:38 UTC
Hi!

We are seeing a strange issue where VPC flow logs are configured but Scout2 is showing them as "NoFlowLog".
I had a look at the report JS file and as you can see, the flow logs are configured and read by Scout2 but are not recognized within the rule as it seems.

Do we miss to configure something? We have not made any changes to AWSScout2/rules/data/findings/vpc-subnet-without-flow-log.json .

Please find attached some more information of the data.

Thanks!

![vpc_flow_logs](https://user-images.githubusercontent.com/15727648/37520876-0520b23c-291f-11e8-8ed1-411a82554800.jpg)
![vpc_flow_logs_findings](https://user-images.githubusercontent.com/15727648/37520878-05417288-291f-11e8-940e-6668542a6471.jpg)

**Comment by schadr** [comment] 2018-05-04 23:04
I'm having the same issue, I installed Scout two yesterday May 3rd using pip

**Comment by j4v** [comment] 2018-06-28 23:30
I believe the issue is that Flow Logs are missing for the subnets even though the VPC that contains said subnets has it activated. @fkpp can you please confirm this is the case?

**Comment by jacobheath** [comment] 2018-07-05 19:22
I am also having this issue, but have noticed that the Flow Logs for my subnets are marked as inherited from the VPC they are attached to, as illustrated in the following screen shot:

![untitled](https://user-images.githubusercontent.com/16947503/42343481-0ed895de-804e-11e8-8e6d-018ede51a553.png)

**Comment by j4v** [comment] 2018-07-06 07:42
Ok thanks, I'll be looking into it.

**Comment by cvemula1** [comment] 2018-07-13 20:20
Same issue with me as well

**Comment by j4v** [comment] 2018-07-16 15:03
@fkpp, @schadr, @jacobheath, @cvemula1 could you please run branch https://github.com/nccgroup/Scout2/tree/issue_251 and confirm that the issue is resolved.

**Closed** 2018-07-20 10:41 UTC
Labels: bug
