### ISSUE TITLE
Errors processing rules from iam-inline-policy-for-role.json

### ISSUE THREAD

**Issue by jwilberding** [nccgroup/Scout2#99] opened 2016-08-25 23:08 UTC
I am unable to run the `default.json` rule set without removing all those related to `iam-inline-policy-for-role.json`.

I am using Python 2.7, and here is the log I get when I add `--debug`.

```
Processing iam rule: "Inline user policy allows sts:AssumeRole *"
sts:AssumeRole
Traceback (most recent call last):
  File "/Users/jwilberding/code/nccgroup/Scout2/AWSScout2/utils.py", line 389, in get_value_at
    target_obj = target_obj[p]
TypeError: string indices must be integers

sts:AssumeRole
Traceback (most recent call last):
  File "/Users/jwilberding/code/nccgroup/Scout2/AWSScout2/utils.py", line 393, in get_value_at
    raise Exception
Exception

Failed to process rule defined in iam-inline-user-policy-allows-sts-AssumeRole.json
Traceback (most recent call last):
  File "Scout2.py", line 170, in main
    aws_config['services'][service]['violations'][rule]['items'] = recurse(aws_config['services'], aws_config['services'], path, [], rules[finding_path][rule], True)
  File "/Users/jwilberding/code/nccgroup/Scout2/AWSScout2/utils.py", line 301, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/jwilberding/code/nccgroup/Scout2/AWSScout2/utils.py", line 301, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/jwilberding/code/nccgroup/Scout2/AWSScout2/utils.py", line 308, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path, config, add_suffix)
  File "/Users/jwilberding/code/nccgroup/Scout2/AWSScout2/utils.py", line 301, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/jwilberding/code/nccgroup/Scout2/AWSScout2/utils.py", line 308, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path, config, add_suffix)
  File "/Users/jwilberding/code/nccgroup/Scout2/AWSScout2/utils.py", line 301, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/jwilberding/code/nccgroup/Scout2/AWSScout2/utils.py", line 301, in recurse
    results = results + recurse(all_info, current_info[attribute], target_path, split_path, config, add_suffix)
  File "/Users/jwilberding/code/nccgroup/Scout2/AWSScout2/utils.py", line 308, in recurse
    results = results + recurse(all_info, split_current_info, split_target_path, split_current_path, config, add_suffix)
  File "/Users/jwilberding/code/nccgroup/Scout2/AWSScout2/utils.py", line 287, in recurse
    if pass_conditions(all_info, current_path, copy.deepcopy(config['conditions'])):
  File "/Users/jwilberding/code/nccgroup/Scout2/AWSScout2/utils.py", line 336, in pass_conditions
    target_obj = get_value_at(all_info, current_path, path_to_value)
  File "/Users/jwilberding/code/nccgroup/Scout2/AWSScout2/utils.py", line 397, in get_value_at
    raise Exception
Exception

Traceback (most recent call last):
  File "Scout2.py", line 267, in <module>
    sys.exit(main(args))
  File "Scout2.py", line 176, in main
    aws_config['services'][service]['violations'][rule]['flagged_items'] = len(aws_config['services'][service]['violations'][rule]['items'])
KeyError: 'items'
```

Any ideas what may be going on? Thanks!

**Comment by l01cd3v** [comment] 2016-08-26 01:13
I was able to reproduce the issue. It is caused by policies whose statement is not a list, but a single dictionary. Working on a fix now.

**Comment by l01cd3v** [comment] 2016-08-26 01:57
This should be fixed in the dev branch, could you please confirm before I merge into master? Thanks !

**Comment by ajlanghorn** [comment] 2016-08-28 23:19
Have also experienced this. Checking 86c29d1 fixes it, before I give a 👍.

**Comment by jwilberding** [comment] 2016-08-29 16:03
Can confirm, thanks for the quick fix!

**Comment by l01cd3v** [comment] 2016-09-08 15:37
This was merged to master. Marking as fixed

**Closed by l01cd3v** 2016-09-08 15:37 UTC
Labels: bug
