### ISSUE TITLE
Automatically process killed by itself

### ISSUE THREAD

**Issue by rammohanreddy86** [nccgroup/Scout2#198] opened 2017-10-10 13:49 UTC
Fetching IAM config...
              groups           policies              roles              users  credential_report    password_policy
                 6/6              43/43              20/20              31/31                1/1                1/1
Fetching Route53Domains config...
             domains
                 1/1
Fetching SES config...
             regions         identities
                 3/3                2/2
Fetching RDS config...
             regions   parameter_groups          instances          snapshots    security_groups      subnet_groups
               14/14                3/3                2/2              18/18              14/14                1/1
Fetching CloudTrail config...
             regions             trails
               14/14              14/14
Fetching ELB config...
             regions               elbs
               14/14                0/0
Fetching EFS config...
             regions       file_systems
                 5/5                2/2
Fetching ELBV2 config...
             regions                lbs       ssl_policies
               14/14                1/1                5/5
Fetching CloudWatch config...
             regions             alarms
               14/14              55/55
Fetching RedShift config...
             regions   parameter_groups           clusters    security_groups
Killed

**Comment by l01cd3v** [comment] 2017-10-10 13:50
Try running with --thread-config 1 ?

**Comment by l01cd3v** [comment] 2017-10-10 13:51
For more info: the threading is likely to be too aggressive for the type of machine you're running the tool on . --thread-config defaults to 4, and values between 1 and 5 are accepted.

**Comment by rammohanreddy86** [comment] 2017-10-10 13:55
Failed with below error.
usage: Scout2 [-h] [--debug] [--force] [--profile PROFILE [PROFILE ...]]
              [--regions REGIONS [REGIONS ...]]
              [--partition-name PARTITION_NAME] [--vpc VPC [VPC ...]]
              [--ip-ranges IP_RANGES [IP_RANGES ...]]
              [--ip-ranges-name-key IP_RANGES_NAME_KEY]
              [--mfa-serial MFA_SERIAL] [--mfa-code MFA_CODE]
              [--csv-credentials CSV_CREDENTIALS] [--report-dir REPORT_DIR]
              [--timestamp [TIMESTAMP]]
              [--exceptions EXCEPTIONS [EXCEPTIONS ...]]
              [--services SERVICES [SERVICES ...]]
              [--skip SKIPPED_SERVICES [SKIPPED_SERVICES ...]] [-l] [--resume]
              [--update] [--ruleset [RULESET]] [--no-browser]
Scout2: error: unrecognized arguments: --thread-config 1

**Comment by l01cd3v** [comment] 2017-10-10 13:56
Sorry this is only on the dev branch ; try running `git checkout origin/dev -b dev` first

**Comment by rammohanreddy86** [comment] 2017-10-10 14:02
Ran the above command, what next i need to do.
# git checkout origin/dev -b dev
Branch dev set up to track remote branch dev from origin.
Switched to a new branch 'dev'

**Comment by l01cd3v** [comment] 2017-10-10 14:03
Try running scout2 with --thread-config 1

**Comment by rammohanreddy86** [comment] 2017-10-10 19:09
Still the same issue.

**Comment by aheifetz** [comment] 2017-10-14 12:29
I think I can confirm the threading issue.   I was trying on AWS t2.micro (both aws linux and ubuntu) and the program would crash either on fetch EC2 or VPC information.   I would  always lose ssh access so I was never able to log back into the machine to really diagnose the issue.   I upgrade to a M4.large and the program run without issue.

**Comment by l01cd3v** [comment] 2017-10-18 17:56
I wonder if this can be due to memory issues, the threading shouldn't be a problem anymore...

**Comment by l01cd3v** [comment] 2017-11-16 16:35
I'm going to close this issue for now and mark it as wontfix - I updated the README to mention that the tool will fail on t2.micro instances and that it's meant to be run on hardware equivalent to a laptop.

**Closed** 2017-11-16 16:35 UTC
Labels: bug, wontfix
