### ISSUE TITLE
KeyError in rules/preprocessing.py (VPC)

### ISSUE THREAD

**Issue by andresriancho** [nccgroup/Scout2#296] opened 2018-09-10 18:13 UTC
KeyError in rules/preprocessing.py
```
Traceback (most recent call last):
  File "/home/andres/tools/virtualenvs/scout2/local/lib/python2.7/site-packages/AWSScout2-3.2.1-py2.7.egg/AWSScout2/rules/preprocessing.py", line 632, in new_go_to_and_do
    callback(aws_config, current_config[key][value], path, current_path, value, callback_args)
  File "/home/andres/tools/virtualenvs/scout2/local/lib/python2.7/site-packages/AWSScout2-3.2.1-py2.7.egg/AWSScout2/rules/preprocessing.py", line 537, in sort_vpc_flow_logs_callback
    subnet_path = combine_paths(current_path[0:4], ['vpcs', subnet_map[attached_resource]['vpc_id'], 'subnets', attached_resource])
KeyError: u'subnet-fd136d8a'
```

KeyError: None in rules/preprocessing.py
```
Traceback (most recent call last):
  File "/home/andres/tools/virtualenvs/scout2/local/lib/python2.7/site-packages/AWSScout2-3.2.1-py2.7.egg/AWSScout2/rules/preprocessing.py", line 632, in new_go_to_and_do
    callback(aws_config, current_config[key][value], path, current_path, value, callback_args)
  File "/home/andres/tools/virtualenvs/scout2/local/lib/python2.7/site-packages/AWSScout2-3.2.1-py2.7.egg/AWSScout2/rules/preprocessing.py", line 284, in match_instances_and_subnets_callback
    vpc = subnet_map[subnet_id]
KeyError: None
```

KeyError in rules/preprocessing.py (VPC)
```
Traceback (most recent call last):
  File "/home/andres/tools/virtualenvs/scout2/local/lib/python2.7/site-packages/AWSScout2-3.2.1-py2.7.egg/AWSScout2/rules/preprocessing.py", line 632, in new_go_to_and_do
    callback(aws_config, current_config[key][value], path, current_path, value, callback_args)
  File "/home/andres/tools/virtualenvs/scout2/local/lib/python2.7/site-packages/AWSScout2-3.2.1-py2.7.egg/AWSScout2/rules/preprocessing.py", line 352, in process_vpc_peering_connections_callback
    target = aws_config['services']['vpc']['regions'][region]['vpcs'][vpc_id]
KeyError: u'vpc-162a7f2a'
```

**Comment by j4v** [comment] 2018-09-10 18:14
Could you please provide more details about the issue (full output with `--debug` flag) please.

**Comment by j4v** [comment] 2018-09-10 18:16
Additionally please merge all you error outputs into a single issue, this is likely the same root cause.

**Comment by j4v** [comment] 2018-11-14 15:07
Closing as this should be resolved in the latest version of https://github.com/nccgroup/ScoutSuite.

**Closed by j4v** 2018-11-14 15:07 UTC
Labels: bug, component-core, component-provider-aws, potential
