### ISSUE TITLE
Cloudtrail not configured / Shows empty region list on the left menu

### ISSUE THREAD

**Issue by andresriancho** [nccgroup/Scout2#300] opened 2018-09-11 12:52 UTC
```
[andres:~/tools/Scout2] [scout2] master* ± python Scout2.py --services cloudtrail --report-dir=cloudtrail --debug --force
Fetching CloudTrail config...
             regions             trails
               15/15                9/9
Processing CloudTrail config...
Matching EC2 instances and IAM roles...
Loading ruleset /home/andres/tools/Scout2/AWSScout2/rules/data/rulesets/default.json
Processing IAM rule[iam-password-policy-reuse-enabled.json]: "Password reuse enabled"
Processing ELBV2 rule[elbv2-no-access-logs.json]: "Lack of access logs"
Processing ELBV2 rule[elbv2-no-deletion-protection.json]: "Lack of deletion protection"
Processing EC2 rule[ec2-ebs-volume-not-encrypted.json]: "EBS volume not encrypted"
Processing CloudTrail rule[cloudtrail-no-global-services-logging.json]: "Global services logging disabled"
Processing CloudTrail rule[cloudtrail-duplicated-global-services-logging.json]: "Global service logging duplicated"
Processing ELBV2 rule[elbv2-older-ssl-policy.json]: "Older SSL/TLS policy"
Processing IAM rule[iam-inline-policy-for-role.json]: "Inline role policy allows iam:PassRole *"
Processing IAM rule[iam-inline-policy-for-role.json]: "Inline role policy allows sts:AssumeRole *"
Processing IAM rule[iam-inline-policy-allows-NotActions.json]: "Inline role policy allows NotActions"
Processing RedShift rule[redshift-cluster-no-version-upgrade.json]: "Version upgrade disabled"
Processing RedShift rule[redshift-cluster-database-not-encrypted.json]: "Cluster database encryption disabled"
Processing RedShift rule[redshift-cluster-publicly-accessible.json]: "Cluster publicly accessible"
Processing IAM rule[iam-inline-policy-for-role.json]: "Inline user policy allows iam:PassRole *"
Processing IAM rule[iam-inline-policy-for-role.json]: "Inline user policy allows sts:AssumeRole *"
Processing IAM rule[iam-inline-policy-allows-NotActions.json]: "Inline user policy allows NotActions"
Processing IAM rule[iam-ec2-role-without-instances.json]: "Unused role for EC2"
Processing CloudWatch rule[cloudwatch-alarm-without-actions.json]: "Alarm without action"
Processing IAM rule[iam-assume-role-lacks-external-id-and-mfa.json]: "Cross-account AssumeRole policy lacks external ID and MFA"
Processing IAM rule[iam-assume-role-policy-allows-all.json]: "AssumeRole policy allows all principals"
Processing RDS rule[rds-instance-short-backup-retention-period.json]: "Short backup retention period"
Processing RDS rule[rds-instance-backup-disabled.json]: "Backup disabled"
Processing RDS rule[rds-instance-single-az.json]: "Single AZ RDS instance"
Processing RDS rule[rds-instance-no-minor-upgrade.json]: "Auto minor version upgrade disabled"
Processing RDS rule[rds-instance-storage-not-encrypted.json]: "Instance storage not encrypted"
Processing CloudFormation rule[cloudformation-stack-with-role.json]: "Role passed to stack"
Processing EC2 rule[ec2-security-group-opens-plaintext-port.json]: "FTP port open"
Processing EC2 rule[ec2-security-group-opens-plaintext-port.json]: "Telnet port open"
Processing EC2 rule[ec2-security-group-opens-port-range.json]: "Use of port ranges"
Processing EC2 rule[ec2-security-group-opens-all-ports.json]: "All ports open"
Processing IAM rule[iam-managed-policy-no-attachments.json]: "Managed policy not attached to any entity"
Processing RDS rule[rds-snapshot-public.json]: "Publicly accessible snapshot"
Processing EC2 rule[ec2-security-group-opens-all-ports-to-all.json]: "All ports open to all"
Processing EC2 rule[ec2-security-group-opens-port-to-all.json]: "TCP port open to all"
Processing EC2 rule[ec2-security-group-opens-port-to-all.json]: "UDP port open to all"
Processing EC2 rule[ec2-security-group-opens-known-port-to-all.json]: "MySQL port open to all"
Processing EC2 rule[ec2-security-group-opens-known-port-to-all.json]: "DNS port open to all"
Processing EC2 rule[ec2-security-group-opens-known-port-to-all.json]: "MongoDB port open to all"
Processing EC2 rule[ec2-security-group-opens-known-port-to-all.json]: "MsSQL port open to all"
Processing EC2 rule[ec2-security-group-opens-known-port-to-all.json]: "Oracle DB port open to all"
Processing EC2 rule[ec2-security-group-opens-known-port-to-all.json]: "PostgreSQL port open to all"
Processing EC2 rule[ec2-security-group-opens-known-port-to-all.json]: "RDP port open to all"
Processing EC2 rule[ec2-security-group-opens-known-port-to-all.json]: "SSH port open to all"
Processing EC2 rule[ec2-security-group-opens-known-port-to-all.json]: "NFS port open to all"
Processing EC2 rule[ec2-security-group-opens-known-port-to-all.json]: "SMTP port open to all"
Processing EC2 rule[ec2-security-group-whitelists-aws.json]: "Security group whitelists AWS CIDRs"
Processing IAM rule[iam-inline-policy-for-role.json]: "Inline group policy allows iam:PassRole *"
Processing IAM rule[iam-inline-policy-for-role.json]: "Inline group policy allows sts:AssumeRole *"
Processing IAM rule[iam-inline-policy-allows-NotActions.json]: "Inline group policy allows NotActions"
Processing RedShift rule[redshift-security-group-whitelists-all.json]: "Security group allows all"
Processing EC2 rule[ec2-default-security-group-in-use.json]: "Default security groups in use"
Processing EC2 rule[ec2-unused-security-group.json]: "Unused security groups"
Processing S3 rule[s3-bucket-world-acl.json]: "Bucket world-listable (anonymous)"
Processing S3 rule[s3-bucket-world-acl.json]: "Bucket's permissions world-readable (anonymous)"
Processing S3 rule[s3-bucket-world-acl.json]: "Bucket world-writable (anonymous)"
Processing S3 rule[s3-bucket-world-acl.json]: "Bucket's permissions world-writable (anonymous)"
Processing S3 rule[s3-bucket-world-acl.json]: "Bucket world-listable"
Processing S3 rule[s3-bucket-world-acl.json]: "Bucket's permissions world-readable"
Processing S3 rule[s3-bucket-world-acl.json]: "Bucket world-writable"
Processing S3 rule[s3-bucket-world-acl.json]: "Bucket's permissions world-writable"
Processing IAM rule[iam-managed-policy-allows-NotActions.json]: "Managed policy allows NotActions"
Processing IAM rule[iam-managed-policy-for-role.json]: "Managed policy allows iam:PassRole *"
Processing IAM rule[iam-managed-policy-for-role.json]: "Managed policy allows sts:AssumeRole *"
Processing IAM rule[iam-user-no-key-rotation.json]: "Lack of key rotation (Active)"
Processing IAM rule[iam-user-no-key-rotation.json]: "Lack of key rotation (Inactive)"
Processing CloudTrail rule[cloudtrail-no-log-file-validation.json]: "Log file validation disabled"
Processing CloudTrail rule[cloudtrail-no-logging.json]: "Logging disabled"
Processing SNS rule[sns-topic-world-policy.json]: "Publish authorized to all principals"
Processing SNS rule[sns-topic-world-policy.json]: "Subscribe authorized to all principals"
Processing SNS rule[sns-topic-world-policy.json]: "Receive authorized to all principals"
Processing SNS rule[sns-topic-world-policy.json]: "AddPermission authorized to all principals"
Processing SNS rule[sns-topic-world-policy.json]: "RemovePermission authorized to all principals"
Processing SNS rule[sns-topic-world-policy.json]: "SetTopicAttributes authorized to all principals"
Processing SNS rule[sns-topic-world-policy.json]: "DeleteTopic authorized to all principals"
Processing Route53 rule[route53-domain-no-autorenew.json]: "Domain not set to autorenew"
Processing Route53 rule[route53-domain-transferlock-not-authorized.json]: "Domain transfer lock not supported by TLD"
Processing Route53 rule[route53-domain-no-transferlock.json]: "Domain transfer not locked"
Processing SQS rule[sqs-queue-world-policy.json]: "SendMessage authorized to all principals"
Processing SQS rule[sqs-queue-world-policy.json]: "ReceiveMessage authorized to all principals"
Processing SQS rule[sqs-queue-world-policy.json]: "PurgeQueue authorized to all principals"
Processing SQS rule[sqs-queue-world-policy.json]: "DeleteMessage authorized to all principals"
Processing SQS rule[sqs-queue-world-policy.json]: "ChangeMessageVisibility authorized to all principals"
Processing SQS rule[sqs-queue-world-policy.json]: "GetQueueAttributes authorized to all principals"
Processing SQS rule[sqs-queue-world-policy.json]: "GetQueueUrl authorized to all principals"
Processing RedShift rule[redshift-parameter-group-logging-disabled.json]: "User activity logging disabled"
Processing RedShift rule[redshift-parameter-group-ssl-not-required.json]: "SSL not required"
Processing CloudTrail rule[cloudtrail-not-configured.json]: "Not configured"
Processing IAM rule[iam-role-with-inline-policies.json]: "Role with inline policies"
Processing IAM rule[iam-group-with-no-users.json]: "Group with no users"
Processing IAM rule[iam-group-with-inline-policies.json]: "Group with inline policies"
Processing RDS rule[rds-security-group-allows-all.json]: "Security group allows all IP addresses"
Processing ELB rule[elb-no-access-logs.json]: "Lack of access logs"
Processing IAM rule[iam-user-with-policies.json]: "User with inline policies"
Processing IAM rule[iam-user-with-multiple-access-keys.json]: "User with multiple API keys"
Processing IAM rule[iam-user-without-mfa.json]: "User without MFA"
Processing VPC rule[vpc-custom-network-acls-allow-all.json]: "Network ACLs allow all ingress traffic (custom)"
Processing VPC rule[vpc-custom-network-acls-allow-all.json]: "Network ACLs allow all egress traffic (custom)"
Processing VPC rule[vpc-network-acl-not-used.json]: "Unused network ACLs"
Processing VPC rule[vpc-default-network-acls-allow-all.json]: "Network ACLs allow all ingress traffic (default)"
Processing VPC rule[vpc-default-network-acls-allow-all.json]: "Network ACLs allow all egress traffic (default)"
Processing SES rule[ses-identity-world-policy.json]: "SendEmail authorized to all principals"
Processing SES rule[ses-identity-world-policy.json]: "SendRawEmail authorized to all principals"
Processing EC2 rule[ec2-default-security-group-with-rules.json]: "Non-empty rulesets for default security groups"
Processing VPC rule[vpc-subnet-with-bad-acls.json]: "Subnet with allow all ingress NACLs"
Processing VPC rule[vpc-subnet-with-bad-acls.json]: "Subnet with allow all egress NACLs"
Processing VPC rule[vpc-subnet-without-flow-log.json]: "Subnet without a flow log"
Processing VPC rule[vpc-subnet-without-flow-log.json]: "Subnet without a flow log"
Processing S3 rule[s3-bucket-no-versioning.json]: "Bucket without versioning"
Processing S3 rule[s3-bucket-no-default-encryption.json]: "Bucket without default encryption enabled"
Processing S3 rule[s3-bucket-no-mfa-delete.json]: "Versioned bucket without MFA delete"
Processing S3 rule[s3-bucket-allowing-cleartext.json]: "Bucket allowing clear text (HTTP) communication"
Processing S3 rule[s3-bucket-no-logging.json]: "Bucket access logging disabled"
Processing IAM rule[iam-password-policy-minimum-length.json]: "Minimum password length too short"
Processing EC2 rule[ec2-security-group-opens-all-ports-to-self.json]: "Unrestricted network traffic within security group"
Processing S3 rule[s3-bucket-world-policy-star.json]: "All actions authorized to all principals"
Processing S3 rule[s3-bucket-world-policy-arg.json]: "Delete actions authorized to all principals"
Processing S3 rule[s3-bucket-world-policy-arg.json]: "Get actions authorized to all principals"
Processing S3 rule[s3-bucket-world-policy-arg.json]: "List actions authorized to all principals"
Processing S3 rule[s3-bucket-world-policy-arg.json]: "Put actions authorized to all principals"
Processing S3 rule[s3-bucket-world-policy-arg.json]: "Manage actions authorized to all principals"
Processing IAM rule[iam-password-policy-no-expiration.json]: "Password expiration disabled"
Processing IAM rule[iam-root-account-used-recently.json]: "Root account used recently"
Processing IAM rule[iam-root-account-no-mfa.json]: "Lack of MFA (root account)"
Processing IAM rule[iam-root-account-with-active-certs.json]: "Root account has active X.509 certs"
Processing IAM rule[iam-root-account-with-active-keys.json]: "Root account has active keys"
Loading ruleset /home/andres/tools/Scout2/AWSScout2/rules/data/rulesets/filters.json
Processing EC2 rule[ec2-security-group-with-public-cidr-grant.json]: "Security group whitelists public CIDRs"
Processing EC2 rule[ec2-instance-with-open-nacls.json]: "Public instance with open NACLs"
Processing IAM rule[iam-role-for-service.json]: "Role for EC2"
Processing IAM rule[iam-role-for-service.json]: "Role for Lambda"
Processing IAM rule[iam-role-for-aws-account.json]: "Role for same account"
Processing IAM rule[iam-role-for-aws-account.json]: "Role for cross account"
Processing S3 rule[s3-bucket-website-enabled.json]: "Bucket with static website enabled"
Searching for profiles matching ['default'] in /home/andres/.aws/credentials ... 
Searching for profiles matching ['default'] in /home/andres/.aws/config ... 
Saving data to cloudtrail/inc-awsconfig/aws_config.js
Saving config...
Saving data to cloudtrail/inc-awsconfig/exceptions.js
Saving config...
Creating cloudtrail/report.html ...
Opening the HTML report...
[andres:~/tools/Scout2] [scout2] master*
```

file:///home/andres/tools/Scout2/cloudtrail/report.html#services.cloudtrail.findings.cloudtrail-not-configured.items

![screenshot from 2018-09-11 09-51-29](https://user-images.githubusercontent.com/865200/45361330-4ade0e80-b5a8-11e8-81d5-d00818aec5a9.png)

**Comment by andresriancho** [comment] 2018-09-11 12:52
The JavaScript console doesn't show any errors / exceptions.

**Comment by andresriancho** [comment] 2018-09-11 12:53
The JS file looks like:

```
                "cloudtrail-not-configured": {
                    "checked_items": 15,
                    "dashboard_name": "Regions",
                    "description": "Not configured",
                    "flagged_items": 6,
                    "id_suffix": "NotConfigured",
                    "items": [
                        "cloudtrail.regions.ap-south-1.NotConfigured",
                        "cloudtrail.regions.eu-west-2.NotConfigured",
                        "cloudtrail.regions.ca-central-1.NotConfigured",
                        "cloudtrail.regions.ap-northeast-2.NotConfigured",
                        "cloudtrail.regions.us-east-2.NotConfigured",
                        "cloudtrail.regions.eu-west-3.NotConfigured"
                    ],
                    "level": "danger",
                    "path": "cloudtrail.regions.id",
                    "rationale": "CloudTrail is not configured, which means that API activity is not logged.",
                    "service": "CloudTrail"
                }
```

**Comment by j4v** [comment] 2018-09-11 17:43
Thanks for the details. This is a duplicate of https://github.com/nccgroup/Scout2/issues/241.

**Closed** 2018-09-11 17:59 UTC
Labels: bug, duplicate
