### ISSUE TITLE
Ability to use EC2 role switching without credentials

### ISSUE THREAD

**Issue by jjegg** [nccgroup/Scout2#197] opened 2017-10-05 07:34 UTC
Does Scout2 support EC2 role switching? I am looking at deploying an EC2 server with an attached role that has a custom policy. This role then has access to role switch into other AWS accounts.

Question being, does Scout2 support the use of no credentials and instead harness the ability of EC2 role switching?

**Comment by l01cd3v** [comment] 2017-10-05 14:34
I haven't tried it but *think* it may work if you put the following in a ~/.aws/config file for each role you want to assume:

[profile foo]
role_arn = .....
source_profile = default

Then run Scout2 with --profile foo

**Comment by jjegg** [comment] 2017-10-05 16:55
Ok, but do you know how it would work with regards to credentials not existing in a file and using EC2 instance profile for role switching?

**Comment by l01cd3v** [comment] 2017-10-05 22:38
The EC2 instance's credentials may be referred to as the "default" profile, which is why the above works. You instruct Scout2 (opinel actually, which is where the code handling credentials / profiles is located), to use the default profile (EC2 credentials if present) and use these to assume the specified role. Then use the assumed credentials to run Scout2.

I just created a couple of roles in a test environment, span up an EC2 instance, and confirmed this works.

**Comment by ohuk2** [comment] 2017-10-09 13:04
Unfortunately that doesn't work for me - I can do "aws s3 ls --profile ..." OK but not with Scout2. Any thoughts...?

Scout2]$ aws s3 ls --profile foo
Enter MFA code:
2017-09-07 07:10:46 xxxxxxxxxxxx
[...]

Scout2]$ Scout2 --profile foo
Error: could not find AWS credentials. Use the --help option for more information.

[bar]
aws_access_key_id = XXXXXXXXX
aws_secret_access_key = yyyyyyyyy

[foo]
role_arn = arn:aws:iam::111111111111:role/.../cyber
source_profile = bar
mfa_serial = arn:aws:iam::222222222222:mfa/myuserid

I've tried specifying the MFA on the command line as well with no luck:

Scout2]$ Scout2 --profile apollo-app-dev --mfa-serial arn:aws:iam::222222222222:mfa/myuserid --mfa-code 123456
Error: could not find AWS credentials. Use the --help option for more information.

**Comment by l01cd3v** [comment] 2017-10-09 14:06
I _think_ that the mfa_serial should be put next to your access key (in the [bar] profile) since it's associated with these credentials and not necessarily with this role.

Making that change *may* work but it may not be enough because all the docs I've ever read online about configuring roles for the AWS CLI mentioned these should be put in the .aws/config file (e.g. http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-cli.html). Consequently it's possible that my code only checks for roles to assume in there.

Moving the [foo] profile to the .aws/config file should work. I'll look into making the code more flexible in the future.

**Comment by l01cd3v** [comment] 2017-11-14 17:16
I think that the reason was actually this issue, https://github.com/nccgroup/opinel/issues/20, which was just fixed. Will close after I release a new version of opinel

**Comment by l01cd3v** [comment] 2017-11-16 16:36
This should be fixed now

**Closed by l01cd3v** 2017-11-16 16:36 UTC
Labels: bug
